# _Foundations of Applied Mathematics_ Labs: Volume 1

In [1]:
%matplotlib inline

# 15. The Drazin Inverse

In [46]:
from scipy import linalg as la

# The standard Schur decomposition.
A = np.array([[0,0,2],[-3,2,6],[0,0,1]])
T,Z = la.schur(A)
T                       # The eigenvalues (2, 0, and 1) are not sorted.

array([[ 2., -3.,  6.],
       [ 0.,  0.,  2.],
       [ 0.,  0.,  1.]])

In [47]:
# Specify a sorting function to get the desired result.
f = lambda x: abs(x) > 0
T1,Z1,k = la.schur(A, sort=f)
T1

array([[2.        , 0.        , 6.70820393],
       [0.        , 1.        , 2.        ],
       [0.        , 0.        , 0.        ]])

In [48]:
k    # k is the number of columns satisfying the sort,
     # which is the number of nonzero eigenvalues.

2

In [49]:
A = np.random.randint(-9,9,(3,3))
A

array([[-5,  1,  2],
       [-9,  0, -5],
       [ 0, -5, -3]])

In [50]:
# Find the minimum value in the array.
minval = np.min(A)
minval

-9

In [51]:
# Find the location of the minimum value.
loc = np.where(A==minval)
loc

(array([1]), array([0]))